version: '0.1'

services:
  sample:
    container_name: react-madup
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
